from astro.schema import ZodiacSignCollection
from astro.util import ZodiacSign, Polarity, Modality, Element, Point

zodiac_sign_traits = ZodiacSignCollection(
    signs={
        ZodiacSign.aries: {
            "sign": ZodiacSign.aries,
            "polarity": Polarity.yang,
            "modality": Modality.cardinal,
            "element": Element.fire,
            "domicile_traditional": Point.mars,
            "domicile_modern": Point.mars,
            "domicile_asteroid": [],
            "exaltation": Point.sun,
            "triplicity": [Point.sun, Point.jupiter, Point.saturn],
            "bounds": [
                {"ruler": Point.jupiter, "from_degree": 0, "to_degree": 6},
                {"ruler": Point.venus, "from_degree": 6, "to_degree": 12},
                {"ruler": Point.mercury, "from_degree": 12, "to_degree": 20},
                {"ruler": Point.mars, "from_degree": 20, "to_degree": 25},
                {"ruler": Point.saturn, "from_degree": 25, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.mars, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.sun, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.venus, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.venus,
            "fall": Point.saturn,
        },
        ZodiacSign.taurus: {
            "sign": ZodiacSign.taurus,
            "polarity": Polarity.yin,
            "modality": Modality.fixed,
            "element": Element.earth,
            "domicile_traditional": Point.venus,
            "domicile_modern": Point.venus,
            "domicile_asteroid": [Point.ceres],
            "exaltation": Point.moon,
            "triplicity": [Point.venus, Point.moon, Point.mars],
            "bounds": [
                {"ruler": Point.venus, "from_degree": 0, "to_degree": 8},
                {"ruler": Point.mercury, "from_degree": 8, "to_degree": 14},
                {"ruler": Point.jupiter, "from_degree": 14, "to_degree": 22},
                {"ruler": Point.saturn, "from_degree": 22, "to_degree": 27},
                {"ruler": Point.mars, "from_degree": 27, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.moon, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.saturn, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.mars,
            "fall": None,
        },
        ZodiacSign.gemini: {
            "sign": ZodiacSign.gemini,
            "polarity": Polarity.yang,
            "modality": Modality.mutable,
            "element": Element.air,
            "domicile_traditional": Point.mercury,
            "domicile_modern": Point.mercury,
            "domicile_asteroid": [],
            "exaltation": None,
            "triplicity": [Point.saturn, Point.mercury, Point.jupiter],
            "bounds": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 6},
                {"ruler": Point.jupiter, "from_degree": 6, "to_degree": 12},
                {"ruler": Point.venus, "from_degree": 12, "to_degree": 17},
                {"ruler": Point.mars, "from_degree": 17, "to_degree": 24},
                {"ruler": Point.saturn, "from_degree": 24, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.jupiter, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.mars, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.sun, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.jupiter,
            "fall": None,
        },
        ZodiacSign.cancer: {
            "sign": ZodiacSign.cancer,
            "polarity": Polarity.yin,
            "modality": Modality.cardinal,
            "element": Element.water,
            "domicile_traditional": Point.moon,
            "domicile_modern": Point.moon,
            "domicile_asteroid": [Point.ceres],
            "exaltation": Point.jupiter,
            "triplicity": [Point.venus, Point.mars, Point.moon],
            "bounds": [
                {"ruler": Point.mars, "from_degree": 0, "to_degree": 7},
                {"ruler": Point.venus, "from_degree": 7, "to_degree": 13},
                {"ruler": Point.mercury, "from_degree": 13, "to_degree": 19},
                {"ruler": Point.jupiter, "from_degree": 19, "to_degree": 26},
                {"ruler": Point.saturn, "from_degree": 26, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.venus, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.mercury, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.moon, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.saturn,
            "fall": Point.mars,
        },
        ZodiacSign.leo: {
            "sign": ZodiacSign.leo,
            "polarity": Polarity.yang,
            "modality": Modality.fixed,
            "element": Element.fire,
            "domicile_traditional": Point.sun,
            "domicile_modern": Point.sun,
            "domicile_asteroid": [Point.pallas],
            "exaltation": None,
            "triplicity": [Point.sun, Point.jupiter, Point.saturn],
            "bounds": [
                {"ruler": Point.jupiter, "from_degree": 0, "to_degree": 6},
                {"ruler": Point.venus, "from_degree": 6, "to_degree": 11},
                {"ruler": Point.saturn, "from_degree": 11, "to_degree": 18},
                {"ruler": Point.mercury, "from_degree": 18, "to_degree": 24},
                {"ruler": Point.mars, "from_degree": 24, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.saturn, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.jupiter, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.mars, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.saturn,
            "fall": None,
        },
        ZodiacSign.virgo: {
            "sign": ZodiacSign.virgo,
            "polarity": Polarity.yin,
            "modality": Modality.mutable,
            "element": Element.earth,
            "domicile_traditional": Point.mercury,
            "domicile_modern": Point.mercury,
            "domicile_asteroid": [Point.ceres, Point.vesta],
            "exaltation": Point.mercury,
            "triplicity": [Point.mercury, Point.moon, Point.mars],
            "bounds": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 7},
                {"ruler": Point.venus, "from_degree": 7, "to_degree": 17},
                {"ruler": Point.jupiter, "from_degree": 17, "to_degree": 21},
                {"ruler": Point.mars, "from_degree": 21, "to_degree": 28},
                {"ruler": Point.saturn, "from_degree": 28, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.sun, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.venus, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.mercury, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.jupiter,
            "fall": Point.venus,
        },
        ZodiacSign.libra: {
            "sign": ZodiacSign.libra,
            "polarity": Polarity.yang,
            "modality": Modality.cardinal,
            "element": Element.air,
            "domicile_traditional": Point.venus,
            "domicile_modern": Point.venus,
            "domicile_asteroid": [Point.juno, Point.pallas],
            "exaltation": Point.saturn,
            "triplicity": [Point.saturn, Point.mercury, Point.jupiter],
            "bounds": [
                {"ruler": Point.saturn, "from_degree": 0, "to_degree": 6},
                {"ruler": Point.mercury, "from_degree": 6, "to_degree": 14},
                {"ruler": Point.jupiter, "from_degree": 14, "to_degree": 21},
                {"ruler": Point.venus, "from_degree": 21, "to_degree": 28},
                {"ruler": Point.mars, "from_degree": 28, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.moon, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.saturn, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.jupiter, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.mars,
            "fall": Point.sun,
        },
        ZodiacSign.scorpio: {
            "sign": ZodiacSign.scorpio,
            "polarity": Polarity.yin,
            "modality": Modality.fixed,
            "element": Element.water,
            "domicile_traditional": Point.mars,
            "domicile_modern": Point.pluto,
            "domicile_asteroid": [Point.ceres, Point.vesta],
            "exaltation": None,
            "triplicity": [Point.venus, Point.mars, Point.moon],
            "bounds": [
                {"ruler": Point.mars, "from_degree": 0, "to_degree": 7},
                {"ruler": Point.venus, "from_degree": 7, "to_degree": 11},
                {"ruler": Point.mercury, "from_degree": 11, "to_degree": 19},
                {"ruler": Point.jupiter, "from_degree": 19, "to_degree": 24},
                {"ruler": Point.saturn, "from_degree": 24, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.mars, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.sun, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.venus, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.venus,
            "fall": Point.moon,
        },
        ZodiacSign.sagittarius: {
            "sign": ZodiacSign.sagittarius,
            "polarity": Polarity.yang,
            "modality": Modality.mutable,
            "element": Element.fire,
            "domicile_traditional": Point.jupiter,
            "domicile_modern": Point.jupiter,
            "domicile_asteroid": [],
            "exaltation": None,
            "triplicity": [Point.sun, Point.jupiter, Point.saturn],
            "bounds": [
                {"ruler": Point.jupiter, "from_degree": 0, "to_degree": 12},
                {"ruler": Point.venus, "from_degree": 12, "to_degree": 17},
                {"ruler": Point.mercury, "from_degree": 17, "to_degree": 21},
                {"ruler": Point.saturn, "from_degree": 21, "to_degree": 26},
                {"ruler": Point.mars, "from_degree": 26, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.moon, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.saturn, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.mercury,
            "fall": None,
        },
        ZodiacSign.capricorn: {
            "sign": ZodiacSign.capricorn,
            "polarity": Polarity.yin,
            "modality": Modality.cardinal,
            "element": Element.earth,
            "domicile_traditional": Point.saturn,
            "domicile_modern": Point.saturn,
            "domicile_asteroid": [],
            "exaltation": Point.mars,
            "triplicity": [Point.venus, Point.moon, Point.mars],
            "bounds": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 7},
                {"ruler": Point.jupiter, "from_degree": 7, "to_degree": 14},
                {"ruler": Point.venus, "from_degree": 14, "to_degree": 22},
                {"ruler": Point.saturn, "from_degree": 22, "to_degree": 26},
                {"ruler": Point.mars, "from_degree": 26, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.jupiter, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.mars, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.sun, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.moon,
            "fall": Point.jupiter,
        },
        ZodiacSign.aquarius: {
            "sign": ZodiacSign.aquarius,
            "polarity": Polarity.yang,
            "modality": Modality.fixed,
            "element": Element.air,
            "domicile_traditional": Point.saturn,
            "domicile_modern": Point.uranus,
            "domicile_asteroid": [Point.pallas],
            "exaltation": None,
            "triplicity": [Point.saturn, Point.mercury, Point.jupiter],
            "bounds": [
                {"ruler": Point.mercury, "from_degree": 0, "to_degree": 7},
                {"ruler": Point.venus, "from_degree": 7, "to_degree": 13},
                {"ruler": Point.jupiter, "from_degree": 13, "to_degree": 20},
                {"ruler": Point.mars, "from_degree": 20, "to_degree": 25},
                {"ruler": Point.saturn, "from_degree": 25, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.venus, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.mercury, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.moon, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.sun,
            "fall": None,
        },
        ZodiacSign.pisces: {
            "sign": ZodiacSign.pisces,
            "polarity": Polarity.yin,
            "modality": Modality.mutable,
            "element": Element.water,
            "domicile_traditional": Point.jupiter,
            "domicile_modern": Point.jupiter,
            "domicile_asteroid": [],
            "exaltation": Point.venus,
            "triplicity": [Point.venus, Point.mars, Point.moon],
            "bounds": [
                {"ruler": Point.venus, "from_degree": 0, "to_degree": 12},
                {"ruler": Point.jupiter, "from_degree": 12, "to_degree": 16},
                {"ruler": Point.mercury, "from_degree": 16, "to_degree": 19},
                {"ruler": Point.mars, "from_degree": 19, "to_degree": 28},
                {"ruler": Point.saturn, "from_degree": 28, "to_degree": 30},
            ],
            "decans": [
                {"ruler": Point.saturn, "from_degree": 0, "to_degree": 10},
                {"ruler": Point.jupiter, "from_degree": 10, "to_degree": 20},
                {"ruler": Point.mars, "from_degree": 20, "to_degree": 30},
            ],
            "detriment": Point.mercury,
            "fall": None,
        },
    }
)
"""
Associates each zodiac sign with relevant information.

- Reference for essential dignities: 
    https://theastrologypodcast.com/wp-content/uploads/2018/05/essential-dignities-table-large.jpg
"""
